name: Building and pushing a docker image to Amazon ECR
on: [push, pull_request]

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONTAINER_IMAGE: example-container:${{ github.sha }}
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create MySQL Volume and Image
      run: docker volume create mysql_data; docker run --name percona -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mypassword -v mysql_data:/var/lib/mysql percona/percona-server:5.7 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    - name: Create Mautic Volume and Image
      run: docker volume create mautic_data; cd apache; docker build -t mautic_docker_action .
    - name: Setup ECR
      run: |
        $( aws ecr get-login --no-include-email )
    - name: ECHO
      run: echo $AWS_ACCOUNT_ID; echo $AWS_DEFAULT_REGION; echo $AWS_ACCOUNT_ID; echo $AWS_ACCESS_KEY_ID; echo $AWS_SECRET_ACCESS_KEY; echo $CONTAINER_IMAGE
    - name: Tag
      run: cd apache; docker tag mautic_docker_action 054748153214.dkr.ecr.us-east-1.amazonaws.com/example-container:1111
    - name: Tagging docker image
      run: cd apache; docker push 054748153214.dkr.ecr.us-east-1.amazonaws.com/example-container:1111
#    - name: Push to ECR
#      if: github.ref == 'refs/heads/master'
#      run: cd apache; docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE
      
      